### ISSUE TITLE
Configure Eclipse

### ISSUE THREAD

**Issue by christian-steinmeyer** [christian-steinmeyer/MIP#1]
Add M2Eclipse (Maven Plugin)
- [x] @andreas5232
- [x] @li-sa 
- [x] @NicoleIsabellaS
- [x] Chris

Adjust Save Actions according to the list below
- [x] @andreas5232
- [x] @li-sa 
- [x] @NicoleIsabellaS
- [x] Chris

Save Actions:
- Remove 'this' qualifier for non static field accesses
- Remove 'this' qualifier for non static method accesses
- Convert control statement bodies to block
- Convert 'for' loops to enhanced 'for' loops
- Use lambda where possible
- Remove unnecessary parentheses
- Remove unused imports
- Add missing '@Override' annotations
- Add missing '@Override' annotations to implementations of interface methods
- Add missing '@Deprecated' annotations
- Remove unnecessary casts
- Remove unnecessary '$NON-NLS$' tags
- Remove trailing white spaces on all lines
- Correct indentation

**Comment by christian-steinmeyer** [comment]
If Maven is not already installed, you can add M2Eclipse by following
Help > Install New Software > add http://download.eclipse.org/technology/m2e/releases

**Comment by NicoleIsabellaS** [comment]
Everyone is done!
